import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import UserCard from "../../components/userCard";

export const getStaticProps = async ({ params: { userId } }) => {
	const response = await fetch(
		`https://jsonplaceholder.typicode.com/users/${userId}`
	);
	const data = await response.json();

	return {
		props: {
			user: data,
		},
	};
};

export const getStaticPaths = async () => {
	const usersData = await fetch(
		"https://jsonplaceholder.typicode.com/users"
	).then((res) => res.json());
	const paths = usersData.map((user) => ({
		params: {
			userId: `${user.id}`,
		},
	}));

	return { paths, fallback: false };
};

export default function User({ user }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>UsersList</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>User {user.name} </h1>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
